<a href="https://colab.research.google.com/github/CreatorGhost/Artificialintelligence/blob/master/IrisFlowers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import matplotlib.pyplot as pt
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [0]:
data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [77]:
data.head(2)

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa

In [78]:
attributes = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
data.columns = attributes
Y=data[['class']]
Y.replace({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}, inplace=True)


/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4278: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,


In [79]:
Y.head(2)

class
0      0
1      0

In [80]:
data.head(2)

sepal_length  sepal_width  petal_length  petal_width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa

In [0]:
X=data.drop(['class'],axis=1)

In [82]:
dt.head(3)

sepal_length  sepal_width  petal_length  petal_width  class
0           4.9          3.0           1.4          0.2      0
1           4.7          3.2           1.3          0.2      0
2           4.6          3.1           1.5          0.2      0

In [0]:
LR=LinearRegression()

In [84]:
LR.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [107]:
LR.coef_

array([[-0.11021076, -0.04472723,  0.22746691,  0.61014756]])

In [86]:
LR.intercept_

array([0.19369639])

In [110]:
LR.predict([[4.6,3.1,1.5,0.2]])

array([[0.01130237]])

In [57]:
sl=float(input("Sepal_Lenghth: "))
sw=float(input("Sepal_width: "))
pl=float(input("Petal_Lenghth: "))
pw=float(input("Petal_width: "))

Sepal_Lenghth: 6.5
Sepal_width: 3.0
Petal_Lenghth: 5.2
Petal_width: 2.0


In [0]:
ans=lr.predict([[sl,sw,pl,pw]])

In [0]:
a=ans[0,0]

In [60]:
if(a<0 and a<0.6):
  print("Iris-setosa")
if(a>=0.6 and a< 1.5):
  print("Iris-versicolor")
if(a>=1.6):
  print("Iris-virginica")


Iris-virginica


#Using Logestic *Regression*

In [0]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as pt

In [0]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [89]:
attribute=['length_1','width_1','Length_2','width_2','target']
df.columns=attribute
df.head(2)

length_1  width_1  Length_2  width_2       target
0       4.9      3.0       1.4      0.2  Iris-setosa
1       4.7      3.2       1.3      0.2  Iris-setosa

In [0]:
df['flower']=df.target.map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})

In [91]:
df.drop('target',axis=1,inplace=True)
df.head(2)

length_1  width_1  Length_2  width_2  flower
0       4.9      3.0       1.4      0.2       0
1       4.7      3.2       1.3      0.2       0

In [0]:
lr=LogisticRegression()
lr.fit(X,Y)

In [96]:
oo=lr.predict([[5.9,3.0,5.1,1.8]])
type(oo)

numpy.ndarray

In [132]:
lr.predict([[4.6,3.1,1.5,0.2]])

array([0])

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x=df.drop('flower',axis=1)
y=df.flower

In [0]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.10)

In [140]:
lr=LogisticRegression()
lr.fit(xtrain,ytrain)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [141]:
lr.score(xtest,ytest)


0.9333333333333333

In [138]:
lr.predict([[4.6,3.1,1.5,0.2]])

array([0])

In [0]:
ck=lr.predict([[5.9,3.0,5.1,1.8]])

In [116]:
ck

array([2])

In [120]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [121]:
!ls /content/gdrive

'My Drive'


In [122]:
from sklearn.externals import joblib

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [123]:
joblib.dump(lr,'act.pkl')

['act.pkl']

In [124]:
!ls

act.pkl  gdrive  sample_data


In [126]:
!mv act.pkl gdrive

mv: cannot create regular file 'gdrive/act.pkl': Operation not supported


In [0]:
!cd gdrive

In [128]:
!ls

act.pkl  gdrive  sample_data


In [0]:
from google.colab import files

In [0]:
files.download('act.pkl')